### ISSUE TITLE
Where does the board get powered from?

### ISSUE THREAD

**Issue by TechnikWeber** [kareiva/micromodem-pcb#2]
Maybe i misunderstood something, but where dies the board get powered from?
Does it get Power from the Baofeng itself or do i need always power it from USB (on Arduino)?
So if i need a portable version i would need an external battery?

**Comment by kareiva** [comment]
From the README.md:

> 2) Plug the Arduino Nano into your Android phone's USB host

Of course you could get a 3-Volt battery to power it.

The current coming from the Baofeng jack is not enough to power the Arduino.
