### ISSUE TITLE
Cable Wiring

### ISSUE THREAD

**Issue by ido1990** [kareiva/micromodem-pcb#4]
Hi!
Thank you for this nice project.
I just finished soldering everything but I'm not sure how to connect the Baofeng cable.
The colors on my cable are different and the diagrams found online didn't help much.
Do you know what color connected to what 3.5/2.5mm contact?
![found this online](https://github.com/user-attachments/assets/b53222e9-c775-437d-9f81-2848c58b4b59)
Thank you!

**Comment by kareiva** [comment]
SPK and MIC on your diagram go to IN and OUT respectively. You should use the audio (not data) ground, also for the last one, you can check if the PTT works by shorting the circuit on your cable before soldering it.

**Comment by ido1990** [comment]
Thank you for responding,
The only grounds I can think of is MIC- and SPK- but SPK- is also the data ground.
As far as I know, the PTT is triggered by connecting the two sleeves together (mentioned in the picture by PTT).
So according to this, I would need to connect like this:
MIC+ --> OUT
SPK+ --> IN
MIC-/Rx Data/PTT --> PTT
GND --> SPK-/PTT/GND Data

Seems correct?

**Comment by kareiva** [comment]
Although it seems to be correct, please test this before soldering. A simple osciloscope will show you if the SPK/GND combination produces the expected low frequency signals. 

I take no responsibility for wiring issues that might damage your equipment :)

**Comment by ido1990** [comment]
Of course.
I will test everything before soldering :)
Thank you!

**Comment by ido1990** [comment]
Ok,
So everything is working except of the PTT.
When the MicroModem is off and the Baofeng is connected nothing happens but in the moment the MM gets power, the PTT is always on.
Do you have any clue what could go wrong?

**Comment by kareiva** [comment]
Check with a multimeter if the micromodem shorts between ptt and gnd during transmission.

**Comment by ido1990** [comment]
Yes it does.
I just tested it when the Baofeng was off.
When I turn it on, it shorts the PTT. Weird.

**Comment by kareiva** [comment]
I never had any issues with PTT, it worked quite well without any tweaking. I even have a working board somewhere with a Baofeng cable, if you are out of options, I could ship that to you.

**Comment by ido1990** [comment]
That's very generous, thank you!
But I think I would like to have something I built myself if I can :)
If you have time and patience, It would help me to know what's the voltage should be across PTT and GND.
I see 1.2mv which is not the same as when the radio is on (1.6v) so maybe that's the issue.

**Comment by ido1990** [comment]
Found the culprit.
The 2N7000 was bad.
Now it works.
Thank you for your help!

**Comment by kareiva** [comment]
Congrats! So the issue is closed? Would you like to update the docs on the wiring?

**Comment by ido1990** [comment]
Yes.
I will gather all the data from my project and update.
